SELECT 
   AFL.BANK_NAME ,
    AFL.FACILITIES_TYPE, 
    AFL.STATUS, 
    AFLD.FACILITIES_ID,
    MAX(CASE 
        WHEN ALD.DET_ID = AFLD.FACILITIES_ID AND ALD.LOOKUP_ID = 32 
        THEN ALD.LOOKUP_DET_NAME 
        ELSE NULL 
    END) AS FACILITIES_NAME
FROM 
    AB_FACILITIES_LETTER AFL
LEFT JOIN 
    AB_FACILITIES_LETTER_DET AFLD 
    ON AFLD.MAST_ID = AFL.ID
LEFT JOIN 
    AB_LOOKUP_DETAIL ALD 
    ON ALD.DET_ID = AFLD.FACILITIES_ID  -- Adjusted JOIN condition
WHERE 
    AFL.FACILITIES_TYPE = 'FACILITIES MAST'
    AND AFL.ORG_ID = :GV_ORG_ID
GROUP BY 
  AFL.BANK_NAME ,
    AFL.FACILITIES_TYPE,
    AFL.STATUS,
    AFLD.FACILITIES_ID,
    ALD.DET_ID,
    ALD.LOOKUP_DET_NAME ,
     ALD.LOOKUP_ID 

