CREATE MATERIALIZED VIEW MV_AB_FACILITIES_LETTER
REFRESH START WITH SYSDATE
NEXT SYSDATE + 1
AS
SELECT AFL.ID,
       AFL.BANK_NAME,
       AFL.FACILITIES_ID,
       -- Add other fields here
       CASE 
           WHEN TRUNC(AFL.BG_EXPIRE_DATE) = TRUNC(SYSDATE) THEN AFL.AMOUNT
           ELSE NULL
       END AS MATURITY, 
       CASE 
           WHEN TRUNC(AFL.BG_EXPIRE_DATE) = TRUNC(SYSDATE - 1) THEN AFL.AMOUNT
           ELSE NULL
       END AS TOMORROW,
       CASE 
           WHEN TRUNC(AFL.BG_EXPIRE_DATE) = TRUNC(SYSDATE - 2) THEN AFL.AMOUNT
           WHEN TRUNC(AFL.BG_EXPIRE_DATE) < TRUNC(SYSDATE - 2) THEN AFL.AMOUNT
           ELSE NULL
       END AS DAY_AFTER_TOMORROW,
       CASE 
           WHEN TRUNC(AFL.BG_EXPIRE_DATE) > TRUNC(SYSDATE) THEN AFL.AMOUNT
           ELSE NULL
       END AS OVER_DUE
FROM AB_FACILITIES_LETTER AFL
WHERE AFL.FACILITIES_TYPE = 'LIMIT UTILIZATION';



SELECT * FROM  MV_AB_FACILITIES_LETTER AFL


SELECT LAST_REFRESH_DATE
FROM USER_MVIEWS
WHERE MVIEW_NAME = 'MV_AB_FACILITIES_LETTER';
--================================================================


SELECT AFL.ID,
       AFLB.BANK_ID,
       AFLB.BANK_NAME UT,
       AFL.BANK_NAME,
       AFL.FACILITIES_ID,
       MAX(CASE 
            WHEN ALD.DET_ID = AFL.FACILITIES_ID AND LOOKUP_ID = '032'
            THEN ALD.LOOKUP_DET_NAME 
            ELSE NULL 
        END) AS FACILITIES_NAME,
       AFL.FACILITIES_TYPE,
       AFL.STATUS,
       AFL.BG_NATURE,
       MAX(CASE 
            WHEN ALD.DET_ID = AFL.BG_NATURE 
            THEN ALD.LOOKUP_DET_NAME 
            ELSE NULL 
        END) AS NATURE,
       AFL.RATE_QUOTET,
       AFL.COMPANY_NAME,
       MAX(CASE 
            WHEN ASR.SR_ID = AFL.COMPANY_NAME AND ASR.REG_TYPE = 'COMPANY' 
            THEN ASR.REG_NAME 
            ELSE NULL 
        END) AS COMPANY_NAMES,
       AFL.SUPPLIER_ID,
       MAX(CASE 
            WHEN ASR.SR_ID = AFL.SUPPLIER_ID AND ASR.REG_TYPE = 'VENDOR' 
            THEN ASR.PARTY_NAME 
            ELSE NULL 
        END) AS Supplier_Name,
       AFL.BG_TYPE,
       AFL.AMOUNT,
       AFLD.ACCOUNT_NO AS ACCOUNT_NAME,
       AFL.BG_ISSU_DATE,
       AFL.BG_EXPIRE_DATE,
       AFL.BG_NUMBER,
       AFL.AGENCY_ID,
       MAX(CASE 
            WHEN ASR.SR_ID = AFL.AGENCY_ID AND ASR.REG_TYPE = 'AGENCY' 
            THEN ASR.REG_NAME 
            ELSE NULL 
        END) AS Agency_Name,
       AFL.ORDER_PURPOSE,
       MAX(CASE 
            WHEN ALD.DET_ID = AFL.ORDER_PURPOSE 
            THEN ALD.LOOKUP_DET_NAME 
            ELSE NULL 
        END) AS PURPOSE,
       AFL.BG_CATEGORY_ID,
       MAX(CASE 
            WHEN ALD.DET_ID = AFL.BG_CATEGORY_ID 
            THEN ALD.LOOKUP_DET_NAME 
            ELSE NULL 
        END) AS CATEGORY,
       
       -- Materialized View columns
       MV.MATURITY, 
       MV.TOMORROW,
       MV.DAY_AFTER_TOMORROW, 
       MV.OVER_DUE,

       INITCAP(AFL.CREATED_BY) || ' (' || TO_CHAR(AFL.CREATED_ON, 'DD-MON-YYYY HH:MIPM') || ')' AS CREATED_BY,

       CASE WHEN ADR.DOC_ID IS NULL THEN 'NOT IMAGE' ELSE 
            '<a href="http://110.39.163.139:8080/i/AKB/'||ADR.DOC_ID||''||ADR.DOCUMENTS_TYPE||'" target="_blank">Download</a>' 
       END AS DOWNLOAD_LINK

FROM AB_FACILITIES_LETTER AFL
LEFT JOIN AB_SETUP_REGISTRATION ASR ON ASR.SR_ID IN (AFL.SUPPLIER_ID, AFL.AGENCY_ID ,AFL.COMPANY_NAME) 
LEFT JOIN AB_LOOKUP_DETAIL ALD ON ALD.DET_ID IN (AFL.BG_CATEGORY_ID, AFL.ORDER_PURPOSE, AFL.BG_NATURE, AFL.FACILITIES_ID) 
LEFT JOIN AB_DOCUMENT_RECORDS ADR ON ADR.DOC_TYPE_ID = AFL.ID
LEFT JOIN AB_FACILITIES_LETTER_DET AFLD ON AFLD.ID = AFL.ACCOUNT_NO 
LEFT JOIN AB_FACILITIES_LETTER AFLB ON AFLB.BANK_ID = AFL.ID
LEFT JOIN MV_AB_FACILITIES_LETTER MV ON MV.ID = AFL.ID -- Join with Materialized View

WHERE AFL.FACILITIES_TYPE = 'LIMIT UTILIZATION'
AND AFL.ORG_ID = NVL(:GV_ORG_ID,AFL.ORG_ID)
GROUP BY AFL.ID,
         AFL.BANK_NAME,
         AFL.FACILITIES_TYPE,
         AFL.STATUS,
         AFL.BG_NATURE,
         AFL.RATE_QUOTET,
         AFL.BG_NUMBER,
         AFL.COMPANY_NAME,
         AFL.SUPPLIER_ID,
         AFL.BG_TYPE,
         AFL.FACILITIES_ID,
         AFL.AMOUNT,
         AFL.ACCOUNT_NO,
         AFL.BG_ISSU_DATE,
         AFL.BG_EXPIRE_DATE,
         AFL.AGENCY_ID,
         AFL.ORDER_PURPOSE,
         AFL.BG_CATEGORY_ID,
         AFL.CREATED_ON,
         AFLD.ACCOUNT_NO,
         AFL.CREATED_BY,
         ADR.DOC_ID,
         ADR.DOCUMENTS_TYPE,
         AFLB.BANK_ID,
         AFLB.BANK_NAME,
         MV.MATURITY,
         MV.TOMORROW,
         MV.DAY_AFTER_TOMORROW,
         MV.OVER_DUE
ORDER BY AFL.CREATED_ON DESC;

