CREATE MATERIALIZED VIEW MV_AB_FACILITIES_LETTER
REFRESH START WITH SYSDATE
NEXT SYSDATE + 1
AS
SELECT AFL.ID,
       AFL.BANK_NAME,
       AFL.FACILITIES_ID,
       -- Add other fields here
       CASE 
           WHEN TRUNC(AFL.BG_EXPIRE_DATE) = TRUNC(SYSDATE) THEN AFL.AMOUNT
           ELSE NULL
       END AS MATURITY, 
       CASE 
           WHEN TRUNC(AFL.BG_EXPIRE_DATE) = TRUNC(SYSDATE - 1) THEN AFL.AMOUNT
           ELSE NULL
       END AS TOMORROW,
       CASE 
           WHEN TRUNC(AFL.BG_EXPIRE_DATE) = TRUNC(SYSDATE - 2) THEN AFL.AMOUNT
           WHEN TRUNC(AFL.BG_EXPIRE_DATE) < TRUNC(SYSDATE - 2) THEN AFL.AMOUNT
           ELSE NULL
       END AS DAY_AFTER_TOMORROW,
       CASE 
           WHEN TRUNC(AFL.BG_EXPIRE_DATE) > TRUNC(SYSDATE) THEN AFL.AMOUNT
           ELSE NULL
       END AS OVER_DUE
FROM AB_FACILITIES_LETTER AFL
WHERE AFL.FACILITIES_TYPE = 'LIMIT UTILIZATION';



SELECT * FROM  MV_AB_FACILITIES_LETTER AFL


SELECT LAST_REFRESH_DATE
FROM USER_MVIEWS
WHERE MVIEW_NAME = 'MV_AB_FACILITIES_LETTER';
